"""
Export 3D Geometry to OBJ+MTL Format

Converts geometry dict to OBJ file (with normals and material assignments)
and corresponding MTL file (with per-room colors).
"""

import json
from pathlib import Path
from typing import Dict, List
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class OBJExporter:
    """Export 3D geometry to OBJ+MTL format."""
    
    def __init__(self):
        self.vertices = []
        self.normals = []
        self.faces = []
        self.vertex_colors = []
        self.materials = {}
        self.material_assignments = {}  # face_id -> material_name
        
    def load_geometry(self, geometry: Dict):
        """
        Load geometry dict (from wall_extrusion.py).
        
        Args:
            geometry: Dict with vertices, faces, normals, colors
        """
        self.vertices = geometry.get('vertices', [])
        self.normals = geometry.get('normals', [])
        self.faces = geometry.get('faces', [])
        self.vertex_colors = geometry.get('colors', [])
        
        logger.info(f"Loaded geometry: {len(self.vertices)} vertices, {len(self.faces)} faces")
        
    def create_materials_from_colors(self):
        """
        Create MTL materials from unique vertex colors.
        
        Assigns each unique color to a material.
        """
        unique_colors = {}
        
        for face_id, face in enumerate(self.faces):
            # Use color of first vertex in face
            v0_idx = face[0]
            if v0_idx < len(self.vertex_colors):
                color = tuple(self.vertex_colors[v0_idx])
                color_key = f"color_{int(color[0]*255)}_{int(color[1]*255)}_{int(color[2]*255)}"
                
                if color_key not in unique_colors:
                    unique_colors[color_key] = color
                    
                self.material_assignments[face_id] = color_key
        
        self.materials = unique_colors
        logger.info(f"Created {len(self.materials)} materials from unique colors")
        
    def export_mtl(self, mtl_path: Path):
        """
        Export materials to MTL file with optimized settings for Three.js/online viewers.
        
        Args:
            mtl_path: Path to output .mtl file
        """
        lines = []
        lines.append("# Material Library - Optimized for Three.js and Web Viewers")
        lines.append("# Generated by export_obj.py")
        lines.append("")
        
        for mat_name, color in self.materials.items():
            lines.append(f"newmtl {mat_name}")
            # Diffuse color (main color)
            lines.append(f"Kd {color[0]:.3f} {color[1]:.3f} {color[2]:.3f}")
            # Ambient color (for better visibility in low light)
            lines.append(f"Ka {color[0]:.3f} {color[1]:.3f} {color[2]:.3f}")
            # Specular color (reduced for matte appearance, helps with rendering)
            lines.append(f"Ks 0.2 0.2 0.2")
            # Shininess (lower = more matte)
            lines.append(f"Ns 20.0")
            # Opacity (fully opaque)
            lines.append(f"d 1.0")
            lines.append("")
        
        with open(mtl_path, 'w') as f:
            f.write("\n".join(lines))
        
        logger.info(f"Exported MTL file: {mtl_path}")
    
    def export_obj(self, obj_path: Path, mtl_filename: str = "model.mtl"):
        """
        Export geometry to OBJ file.
        
        Args:
            obj_path: Path to output .obj file
            mtl_filename: Filename of MTL file (for mtllib reference)
        """
        lines = []
        
        # Header
        lines.append("# OBJ File - 3D Floor Plan Model")
        lines.append("# Generated by export_obj.py")
        lines.append(f"# Vertices: {len(self.vertices)}")
        lines.append(f"# Faces: {len(self.faces)}")
        lines.append("")
        
        # Material library reference
        lines.append(f"mtllib {mtl_filename}")
        lines.append("")
        
        # Vertices (v x y z)
        lines.append("# Vertices")
        for vert in self.vertices:
            lines.append(f"v {vert[0]:.6f} {vert[1]:.6f} {vert[2]:.6f}")
        lines.append("")
        
        # Normals (vn nx ny nz)
        lines.append("# Normals")
        for normal in self.normals:
            # Normalize normal vector
            length = (normal[0]**2 + normal[1]**2 + normal[2]**2) ** 0.5
            if length > 1e-6:
                normal = [n/length for n in normal]
            lines.append(f"vn {normal[0]:.6f} {normal[1]:.6f} {normal[2]:.6f}")
        lines.append("")
        
        # Faces with material assignments
        lines.append("# Faces")
        current_material = None
        
        for face_id, face in enumerate(self.faces):
            # Switch material if needed
            mat_name = self.material_assignments.get(face_id, "default")
            if mat_name != current_material:
                lines.append(f"usemtl {mat_name}")
                current_material = mat_name
            
            # Face definition: f v1//vn1 v2//vn2 v3//vn3 (vertex//normal, no texture coords)
            # OBJ indices are 1-based
            v1, v2, v3 = face[0] + 1, face[1] + 1, face[2] + 1
            lines.append(f"f {v1}//{v1} {v2}//{v2} {v3}//{v3}")
        
        with open(obj_path, 'w') as f:
            f.write("\n".join(lines))
        
        logger.info(f"Exported OBJ file: {obj_path}")
    
    def export(self, geometry: Dict, output_dir: Path = None) -> Path:
        """
        Full export pipeline: geometry dict -> OBJ + MTL files.
        
        Args:
            geometry: Geometry dict from wall_extrusion
            output_dir: Output directory (default: test_output)
        
        Returns:
            Path to output OBJ file
        """
        if output_dir is None:
            output_dir = Path("test_output")
        
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Load geometry
        self.load_geometry(geometry)
        
        # Create materials
        self.create_materials_from_colors()
        
        # Export files
        obj_path = output_dir / "floor_plan_3d.obj"
        mtl_path = output_dir / "floor_plan_3d.mtl"
        
        self.export_obj(obj_path, mtl_path.name)
        self.export_mtl(mtl_path)
        
        logger.info(f"\n✓ Export complete!")
        logger.info(f"  OBJ file: {obj_path}")
        logger.info(f"  MTL file: {mtl_path}")
        logger.info(f"  Materials: {len(self.materials)}")
        
        return obj_path


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python export_obj.py <geometry_json> [output_dir]")
        sys.exit(1)
    
    geometry_path = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "test_output"
    
    # Load geometry
    with open(geometry_path, 'r') as f:
        geometry = json.load(f)
    
    # Export
    exporter = OBJExporter()
    exporter.export(geometry, Path(output_dir))
